const eventsData = [
    {
        name: "Chess School Holiday Program for Kids",
        date: "2025-04-22T08:00:00",
        location: "Thinknext Chess College Sydney",
        price: 543,
        availability: false,
        type: "music",
    },
    {
        name: "Master the Sydney Market: Strategic Property Investing",
        date: "2025-05-06T19:00:00",
        location: "Sydney",
        price: 830,
        availability: false,
        type: "conference",
    },
    {
        name: "TURMA DO PAGODE // SYDNEY SHOW",
        date: "2025-05-03T15:00:00",
        location: "Fraser Park",
        price: 521,
        availability: true,
        type: "networking",
    },
    {
        name: "European Easter Market",
        date: "2025-04-10T10:00:00",
        location: "Polish Club Ashfield",
        price: 332,
        availability: true,
        type: "conference",
    },
    {
        name: "Sydney's Biggest NEON RAVE Boat Party + Free After Party",
        date: "2025-04-24T20:30:00",
        location: "King Street Wharf - Darling Harbour",
        price: 250,
        availability: true,
        type: "music",
    },
    {
        name: "Garry Uebergang Tribute Dinner",
        date: "2025-05-02T18:30:00",
        location: "Le Montage",
        price: 180,
        availability: true,
        type: "networking",
    },
    {
        name: "Live from Sydney",
        date: "2025-04-30T18:00:00",
        location: "WPP Sydney Campus",
        price: 60,
        availability: false,
        type: "conference",
    },
    {
        name: "SUTRA ELEMENTS FT. JORDAN BRANDO",
        date: "2025-04-19T21:00:00",
        location: "Kinselas Hotel (Oxford St)",
        price: 324,
        availability: true,
        type: "music",
    },
    {
        name: "Concert in the Park",
        date: "2025-08-10T14:00:00",
        location: "Centennial Park",
        price: 150,
        availability: true,
        type: "networking",
    },
    {
        name: "AI Startup Conference",
        date: "2025-09-15T09:00:00",
        location: "Sydney Tech Hub",
        price: 560,
        availability: true,
        type: "conference",
    },
    {
        name: "Charity Fun Run",
        date: "2025-06-22T07:00:00",
        location: "Sydney Harbour",
        price: 45,
        availability: true,
        type: "music",
    },
    {
        name: "Wine Tasting Gala",
        date: "2025-07-14T18:00:00",
        location: "Hunter Valley",
        price: 90,
        availability: true,
        type: "networking",
    },
    {
        name: "Tech Expo 2025",
        date: "2025-11-05T10:00:00",
        location: "International Convention Centre",
        price: 700,
        availability: true,
        type: "conference",
    },
    {
        name: "Comedy Night at The Basement",
        date: "2025-06-12T20:00:00",
        location: "The Basement, Circular Quay",
        price: 120,
        availability: true,
        type: "music",
    },
    {
        name: "Art Exhibition Opening",
        date: "2025-07-20T16:00:00",
        location: "Museum of Modern Art",
        price: 300,
        availability: false,
        type: "conference",
    },
    {
        name: "Food Festival: Tastes of the City",
        date: "2025-08-02T11:00:00",
        location: "Town Hall Square",
        price: 65,
        availability: true,
        type: "music",
    },
    {
        name: "Basketball Championship Finals",
        date: "2025-03-18T17:00:00",
        location: "Qudos Bank Arena",
        price: 410,
        availability: true,
        type: "networking",
    },
    {
        name: "Startup Pitch Night",
        date: "2025-02-28T18:00:00",
        location: "Sydney Innovation Center",
        price: 230,
        availability: true,
        type: "conference",
    },
];

export default eventsData;
