name: CI/CD Pipeline

on:
  push:
    branches: [Hasaan---Sandbox]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({connectionStatus: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5        
          
    env:
      MONGO_URI: mongodb://mongo:27017/eventmanager

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (Backend and Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd website_backend
          npm ci
          
      - name: Install frontend dependencies
        run: |
          cd website_frontend
          npm ci

      - name: Run backend system test
        run: |
          cd website_backend
          npm run test:system
        env:
          MONGO_URI: mongodb://mongo:27017/eventmanager

      - name: Build frontend react
        run: |
          cd: website_frontend
          npm run start

      - name: Simulate Deployment (Create Artifact)
        run: |
          mkdir -p deployment-staging
          cp -r website_frontend/build/* deployment-staging/
          echo "Built and ready to deploy!"
