name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5        
          
        env:
          MONGO_URI: mongodb://localhost:27017/eventmanager
          JWT_SECRET: eventmanagementwebsitekey2025
          CLIENT_ID: 120371016917-iumg08jgnasrkj5m9d54vjdbchsne82g.apps.googleusercontent.com
          CLIENT_SECRET: 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
          REDIRECT_URI: http://localhost:3000/oauth2callback
          ACCESS_TOKEN: ya29.a0AW4Xtxh4O6ul18KuK0bf8rDPIkUjv_P-VJGP8OFJ45DzhLFD3JhEU7vES7igCNj_W8YAQNcHpVePn6oNG4uyiOx_2EENekBtLVWwuL76zt-lbGdyVp0TtgNjH2NIBCb_gmzrkopavd5tMiwN8GlTI8aDRzMTxEtskskx_0nraCgYKAeUSARMSFQHGX2MiKk98iSLTd5sI7OVkQfesBg0175
          REFRESH_TOKEN: 1//04YrqwPThIsdqCgYIARAAGAQSNwF-L9Irj4uCnphTLmabZvLQ1OiQeS-WzxIVegAHHX3YQM4KhnEOamGsqzyhVSt47ZLbGu5-ZBw
          EMAIL_USERNAME: eventmanagermanagement@gmail.com
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (Backend and Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: |
          cd website_backend
          npm ci
          
      - name: Install frontend dependencies
        run: |
          cd website_frontend
          npm ci

      - name: Wait for MongoDB to be ready
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd
          for i in {1..15}; do
            nc -z localhost 27017 && echo "MongoDB is ready!" && break
            echo "Waiting for MongoDB..."
            sleep 3
          done
          
      - name: Start backend server
        run: |
          cd website_backend
          npm run start &
          sleep 5
        env:
          MONGO_URI: mongodb://localhost:27017/eventmanager
          JWT_SECRET: eventmanagementwebsitekey2025

      - name: Run backend system test
        run: |
          cd website_backend
          npm run test:system
        env:
          MONGO_URI: mongodb://localhost:27017/eventmanager
          JWT_SECRET: eventmanagementwebsitekey2025
      
      - name: Build frontend react
        run: |
          cd website_frontend
          npm run build

      - name: Simulate Deployment (Create Artifact)
        run: |
          mkdir -p deployment-staging
          cp -r website_frontend/build/* deployment-staging/
